### ISSUE TITLE
Support for Capacitor 3

### ISSUE THREAD

**Issue by nunoarruda** [cuongpl/capacitor-ios-autofill-save-password#1]
Hi @cuongpl,

Thanks for the handy plugin 👍. This plugin breaks Xcode builds when using Capacitor 3. Do you want to update it to support Capacitor 3?

It looks like @EliArtist partially did it on the fork https://github.com/EliArtist/capacitor-ios-autofill-save-password but I thought to open an issue anyway in case you want to update the plugin in the "official" repo.

TypeScript support would be nice too since the `Plugins` object is deprecated.

Thanks!

**Comment by nunoarruda** [comment]
@cuongpl sorry, I'm a web developer. I have no knowledge of native programming and plugin development. Maybe the following resource might help you update the plugin?
- [Updating Capacitor to 3.0 in your plugin](https://capacitorjs.com/docs/updating/plugins/3-0)

**Comment by cuongpl** [comment]
@nunoarruda Maybe it works on Capacitor 3 now so I close this issue.
