### ISSUE TITLE
Get user's action on prompt dialog

### ISSUE THREAD

**Issue by mavra13** [cuongpl/capacitor-ios-autofill-save-password#11]
Hello!! 
I am currently working on an Ionic-Vue 6/ Capacitor 5 app for iOS devices.
I was wondering if there is a way to get the user's choice on the prompt dialog. 
For example if there is a prompt dialog to ask the user if they want to update the password, how do I grab the user's choice(possible choices: update password/not now)?
I would like to perform some additional actions based on that choice but so far I haven't figured out a way to actually get it.
Thanks!

**Comment by cuongpl** [comment]
@mavra13 I don't know any way to get the user's choice. If there is a way, it's iOS native way.

**Comment by mavra13** [comment]
@cuongpl I feared that would be the case but I thought to ask anyway.
Thank you for your time!
