### ISSUE TITLE
breaking change capacitor 4 to 5 only marked as a patch in the version breaks builds

### ISSUE THREAD

**Issue by j-d-carmichael** [cuongpl/capacitor-ios-autofill-save-password#13]
### Background
- **Original Setup**: Projects are using `capacitor-ios-autofill-save-password` at version `^1.1.4`, compatible with Capacitor v4.
- **Update Released**: A new version `1.1.5` of `capacitor-ios-autofill-save-password` is released, but it introduces changes not compatible with Capacitor v4.

### Issue with Semantic Versioning
- **Semantic Versioning Principle**: Breaking changes should increment the major version number. The update from `1.1.4` to `1.1.5` should have been to `2.0.0` if it introduced breaking changes.
- **The Problem**: The caret `^` in `^1.1.4` allows minor and patch updates. The project automatically updates to `1.1.5`,  causing issues due to incompatibility with Capacitor v4.

### Resolution Steps
1. The maintainers of `capacitor-ios-autofill-save-password` should:
   - Release a new `2.0.0` version for the breaking changes.
   - Optionally, release a patch like `1.1.6` to revert the breaking changes in `1.1.5`.

**Comment by j-d-carmichael** [comment]
Additionally - this package still works perfectly fine with capacitor v4.

The peer dependency could be changed to permit 4 and 5 eg:  "^4 || ^5"

**Comment by cuongpl** [comment]
@j-d-carmichael 
> Release a new 2.0.0 version for the breaking changes.
> Optionally, release a patch like 1.1.6 to revert the breaking changes in 1.1.5.

I fixed it following your suggestion. Thank you.
